Add distance measurement tool
KitwareMedical/SlicerQReads pull request #70
Opened 2021-04-20 18:15 UTC by spycolyf

Please review this code. It is my attempt to implement to Distance Measurement Tool. There is a known issue with the edit function that replaces the QREADS tool bar. The absolute best solution would be to allow the user to get the QREADS toolbar back rather than eliminating the very useful Slicer measurement line edit function.

2021-04-20 19:37 UTC, jcfr requested changes
Consider rebasing the change and addressing comments

2021-04-20 19:37 UTC, jcfr commented on Modules/Scripted/QReads/QReads.py
> +  def createDistMeasTool(self):
No need to abbreviate, consider using fully descriptive name

2021-04-20 19:37 UTC, jcfr commented on Modules/Scripted/QReads/QReads.py
> +    slicer.mrmlScene.AddNode(lineNode)
```python
lineNode.UnRegister(slicer.mrmlScene)
```

See https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MemoryManagement#Python_scripts_and_scripted_modules

2021-04-21 19:51 UTC, jcfr commented
Only the relevant actions are visible when right-clicking:

![image](https://user-images.githubusercontent.com/219043/115612561-6578d800-a2b9-11eb-93ab-083928e169d0.png)

2021-04-21 19:51 UTC, jcfr approved these changes

2021-04-21 19:51 UTC, spycolyf commented
I'm making the following changes:

1) Make the Distance measurement Tool Button a toggle button.
2) When toggle is checked, enable 1 drawing on any image
3) When toggle is unchecked, Delete line.

2021-04-21 19:52 UTC, merged

2021-04-21 19:53 UTC, jcfr commented
> I'm currently making the following changes:

Consider creating a new issue and new branch based on the latest version. Thanks

2021-04-21 19:53 UTC, jcfr commented
> When toggle is unchecked, Delete line.

This has already been implemented using right click.

2021-04-21 19:54 UTC, spycolyf commented
OK, Could you make the Interactive handles also a a right mouse choice if easy to do

2021-04-21 19:58 UTC, jcfr commented
> OK, Could you make the Interactive handles also a a right mouse choice if easy to do

Consider creating an issue and associated the "Backlog" milestone. For now, I consider this is a very minor tweak that should be addressed at later stage after allocating resources for this project.

2021-04-21 19:59 UTC, spycolyf commented
OK